version: '3'

vars:
  WORKFLOWS_DIR: ./workflows
  ACTIVITIES_DIR: ./activities

tasks:
  dev:
    desc: "Start development environment with hot reload"
    cmds:
      - docker-compose up -d
      - task: watch-workflows
      - task: watch-activities

  watch-workflows:
    desc: "Watch workflow files for changes"
    cmds:
      - echo "👀 Watching workflow files..."
      - find {{.WORKFLOWS_DIR}} -name "*.ts" -o -name "*.js" | entr -r task reload-workflows

  watch-activities:
    desc: "Watch activity files for changes"
    cmds:
      - echo "👀 Watching activity files..."
      - find {{.ACTIVITIES_DIR}} -name "*.ts" -o -name "*.js" | entr -r task reload-activities
