version: '3'

tasks:
  clean:
    desc: "Clean all containers, volumes, and build cache"
    cmds:
      - docker-compose down -v --remove-orphans
      - docker system prune -f
      - echo "🧹 Cleaned up"

  reset:
    desc: "Reset everything to clean state"
    cmds:
      - task: stop
      - task: clean
      - rm -rf ~/.n8n postgres_data
      - echo "🔄 Reset complete"

  backup:
    desc: "Backup workflows and data"
    cmds:
      - mkdir -p backups
      - docker-compose exec n8n n8n export:workflow --all --output=../backups/workflows-$(date +%Y%m%d-%H%M%S).json
      - docker run --rm -v n8n_n8n-data:/data -v $(pwd)/backups:/backup alpine tar czf /backup/n8n-data-$(date +%Y%m%d-%H%M%S).tar.gz /data
      - echo "💾 Backup created"

  restore:
    desc: "Restore from backup"
    cmds:
      - task: stop
      - docker run --rm -v n8n_n8n-data:/data -v $(pwd)/backups:/backup alpine tar xzf /backup/{{.BACKUP_FILE}} -C /
      - task: start
      - echo "📥 Restored from backup"
