version: '3'

tasks:
  ui:
    desc: "Open N8N UI in browser"
    cmds:
      - echo "N8N UI http://localhost:5678"

  logs:
    desc: "Show N8N logs"
    cmds:
      - docker-compose logs -f n8n

  logs:db:
    desc: "Show database logs"
    cmds:
      - docker-compose logs -f postgres

  configure-n8n:
    desc: "Configure N8N settings"
    cmds:
      - docker-compose exec n8n n8n configure

  reload-workflows:
    desc: "Reload workflows from code"
    cmds:
      - >
        docker-compose exec n8n node -e "const { loadWorkflows } = require('./lib/workflow-loader');
        loadWorkflows().then(() => console.log('✅ Workflows reloaded'));"

  reload-activities:
    desc: "Reload custom activities"
    cmds:
      - docker-compose restart n8n
      - echo "🔄 Activities reloaded"

  build-activities:
    desc: "Build custom activities"
    cmds:
      - cd activities && npm run build